### ISSUE TITLE
Error when call cp.generate_quadrature

### ISSUE THREAD

**Issue by HieuMaiTrung** [hplgit/chaospy#1]
I have this error when try the example in chaospy. Could anyone let me know what was the problem and how to fix it? I am new in Python. Thank you so much.
Mai

>>> import chaospy as cp
>>> import numpy as np
>>> import odespy
>>> a = cp.Uniform(0, 0.1)
>>> I = cp.Uniform(8, 10)
>>> dist = cp.J(a, I)
>>> order = 5
>>> P, norms = cp.orth_ttr(order, dist, retall=True)
>>> nodes, weights = cp.generate_quadrature(order+1, dist, rule="G")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/trunghieumai/src/chaospy/chaospy/quadrature.py", line 105, in generate_quadrature
    x, w = golub_welsch(order, domain, acc)
  File "/home/trunghieumai/src/chaospy/chaospy/quadrature.py", line 242, in golub_welsch
    for k in range(2*o[d]-3)])
  File "/home/trunghieumai/src/chaospy/chaospy/dist/backend.py", line 399, in mom
    return out.reshape(shape)
ValueError: total size of new array must be unchanged

**Comment by jonathf** [comment]
Ah, yes. It seems I added in the last push.

I removed it now and the software should be functioning again I think. Let me know if that isn't the case, and I'll reopen.
